{
	"openapi": "3.0.0",
	"info": {
		"title": "User List API",
		"version": "1.0.0"
	},
	"paths": {
		"/users": {
			"post": {
				"summary": "Create a new user",
				"requestBody": {
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"type": "object",
								"properties": {
									"name": {
										"type": "string"
									},
									"email": {
										"type": "string"
									}
								},
								"example": {
									"name": "ExampleName",
									"email": "exampleMail@mail.com"
								},
								"required": [
									"name",
									"email"
								]
							}
						}
					}
				},
				"responses": {
					"201": {
						"description": "Created.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/user"
								},
								"examples": {
									"User": {
										"$ref": "#/components/examples/user"
									}
								}
							}
						}
					},
					"400": {
						"description": "This email is already in use.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/requestError"
								},
								"example": {
									"error": "This email is already in use."
								}
							}
						}
					}
				}
			},
			"get": {
				"summary": "Return all the users",
				"parameters": [
					{
						"in": "header",
						"name": "user_id",
						"required": true,
						"schema": {
							"type": "string",
							"example": "1359936d-7bb8-4258-9af9-39ec879e10f9"
						}
					}
				],
				"responses": {
					"200": {
						"description": "Success",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/users"
								},
								"examples": {
									"User": {
										"$ref": "#/components/examples/users"
									}
								}
							}
						}
					},
					"400": {
						"description": "You dont have permission to be here",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/requestError"
								},
								"examples": {
									"permission error": {
										"value": {
											"error": "You don't have permission to be here"
										}
									}
								}
							}
						}
					}
				}
			}
		},
		"/users/{user_id}": {
			"get": {
				"summary": "Return an user profile",
				"parameters": [
					{
						"in": "path",
						"name": "user_id",
						"required": true,
						"schema": {
							"type": "string",
							"example": "1359936d-7bb8-4258-9af9-39ec879e10f9"
						}
					}
				],
				"responses": {
					"200": {
						"description": "Ok",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/user"
								},
								"examples": {
									"User": {
										"$ref": "#/components/examples/user"
									}
								}
							}
						}
					},
					"404": {
						"description": "Not found",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/requestError"
								},
								"example": {
									"error": "User not exists"
								}
							}
						}
					}
				}
			}
		},
		"/users/{user_id}/admin": {
			"patch": {
				"summary": "Make user as admin",
				"parameters": [
					{
						"in": "path",
						"required": true,
						"name": "user_id",
						"schema": {
							"type": "string",
							"example": "7c66032c-df5c-4b22-8fae-04160ad16669"
						}
					}
				],
				"responses": {
					"200": {
						"description": "Ok",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#components/schemas/user"
								},
								"examples": {
									"Admin": {
										"$ref": "#/components/examples/admin"
									}
								}
							}
						}
					},
					"404": {
						"description": "Not found",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/requestError"
								},
								"example": {
									"error": "User not exists"
								}
							}
						}
					}
				}
			}
		}
	},
	"components": {
		"schemas": {
			"user": {
				"type": "object",
				"properties": {
					"id": {
						"type": "string"
					},
					"admin": {
						"type": "boolean"
					},
					"name": {
						"type": "string"
					},
					"email": {
						"type": "string"
					},
					"created_at": {
						"type": "string"
					},
					"updated_at": {
						"type": "string"
					}
				}
			},
			"users": {
				"type": "array",
				"items": {
					"$ref": "#components/schemas/user"
				}
			},
			"requestError": {
				"type": "object",
				"properties": {
					"error": {
						"type": "string"
					}
				}
			}
		},
		"examples": {
			"user": {
				"value": {
					"id": "48cc5d64-ea70-4161-978f-bf4a7e6eceaa",
					"admin": false,
					"name": "ExampleName",
					"created_at": "2022-06-11T20:39:06.570Z",
					"updated_at": "2022-06-11T20:39:06.570Z"
				}
			},
			"users": {
				"value": [
					{
						"id": "874fc29b-a39e-4a31-a296-50aa514ecd5f",
						"admin": false,
						"name": "ExampleName1",
						"email": "exampleMail@mail.com",
						"created_at": "2022-06-11T20:39:06.570Z",
						"updated_at": "2022-06-11T20:39:06.570Z"
					},
					{
						"id": "48cc5d64-ea70-4161-978f-bf4a7e6eceaa",
						"admin": true,
						"name": "ExampleName2",
						"email": "exampleMail2@mail.com",
						"created_at": "2022-06-11T20:39:06.570Z",
						"updated_at": "2022-06-11T20:39:06.570Z"
					}
				]
			},
			"admin": {
				"value": {
					"id": "48cc5d64-ea70-4161-978f-bf4a7e6eceaa",
					"admin": true,
					"name": "Admin",
					"email": "admin@mail.com",
					"created_at": "2022-06-11T20:39:06.570Z",
					"updated_at": "2022-06-11T20:39:06.570Z"
				}
			}
		}
	}
}